version: '3.1'

services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_ROOT: ${DB_ROOT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql/
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "9000:9000"
    volumes:
      - wp_volume:/var/www/
    networks:
      - inception

  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/
    networks:
      - inception

volumes:
  db_volume:
    driver_opts:
      type: none
      o: bind
      device: "/home/lorbke/data/mariadb"
  wp_volume:
    driver_opts:
      type: none
      o: bind
      device: "/home/lorbke/data/wordpress"

networks:
  inception: