version: '3.1'

services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB: ${WORDPRESS_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql/
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    environment:
      WORDPRESS_DB: ${WORDPRESS_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "9000:9000"
    volumes:
      - wp_volume:/var/www/
    networks:
      - inception

  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/
    networks:
      - inception

volumes:
  db_volume:
  wp_volume:

networks:
  inception: